FROM python:3.10-slim

# instalar cliente docker dentro del contenedor
RUN apt-get update && apt-get install -y docker.io && apt-get clean

WORKDIR /pipeline

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt || true

COPY . /pipeline
